import { Metadata } from "next";
import ShortProjectPage from "@/components/short_project_page";

export const metadata: Metadata = {
  title: 'Emotions AI vs Human',
};

export default function AIHUM() {
    const title = "Emotions in AI-generated music compared to emotions in human-composed music";
    const why = "I set out to investigate whether AI-generated music can evoke emotions as effectively as music composed by humans. With the rapid advancement of generative AI, I was curious about its emotional impact on listeners and whether the origin of a musical piece—human or artificial—affects the emotional experience. The core question was whether listeners respond differently to music depending on the composer, and if so, how those differences manifest emotionally.";
    const achieved = "I designed and conducted an online listening experiment using cinematic orchestral music excerpts—two composed by humans and two generated by the AI tool AIVA. Participants rated their felt emotions using a three-dimensional model on a 7-point Likert scale. I ensured methodological rigor by randomizing excerpt order, masking the composer identity, and collecting demographic and listening environment data. The responses were analyzed using the Wilcoxon signed-rank test to identify statistically significant differences in emotional responses between the two composer types.";
    const extra = "The results revealed that while AI-generated music can indeed evoke strong emotions, the emotional profiles differ from those elicited by human-composed music. Notably, AI music produced more varied and less consistent emotional responses, with some participants expressing surprise upon learning the origin of the pieces. These findings suggest that while AI can be emotionally expressive, its output may still lack certain nuances found in human compositions. This study highlighted the importance of thoughtful stimulus selection and participant awareness in future research on AI and emotional perception in music.";
    const skills = ["Experimental Design", "Data Analysis", "Music Psychology"];
    const links = [{ name: "GitHub", href: "https://github.com/mariapolak/MPC-Mini-Project" }];

    return (
        <ShortProjectPage
            title={title}
            image="/hobby/ai_hum/main.png"
            why={why}
            what={achieved}
            results={extra}
            skills={skills}
            links={links}
        />
    );
}